config/routes.rb
Rails.application.routes.draw do
  get 'home' => 'static#home'
  get 'residential' => 'static#home'
  get 'business' => 'static#biz'
  get 'business_pricing' => 'static#bizpricing'
  get 'residential_pricing' => 'static#perpricing'
  get 'about' => 'static#about'
  get 'features' => 'static#features'
  resources :subscribers
  
  
  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users, :only => [:show]
  
  match '/contacts',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]

  root 'static#home'

end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :message
    attribute :nickname,  :captcha  => true
    
    # Declare the e-mail headers. It accepts anything the mail method
    # in ActionMailer accepts.
    def headers
    {
        :subject => "My Contact Form",
        :to => "dialholic@gmail.com",
        :from => %("#{name}" <#{email}>)
    }
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :lines, :numericality => { :greater_than => 0, :less_than_or_equal_to => 100, :message => 
                                          "Number of users must be grater than 0 and less than 100" }
  validates :phone, format: { with: /\d{3}\d{3}\d{4}/, message: "bad format" }
  validates :whichmodel, :presence => true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end

    def create
        @contact = Contact.new(params[:contact])
        @contact.request = request
        if @contact.deliver
            flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
            render :new
        else
            flash.now[:error] = 'Cannot send message.'
            render :new
        end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    '/subscribers/new'
  end
  
  private

  def sign_up_params
    params.require(:user).permit(:whichmodel, :email,:name, :phone, :lines, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:whichmodel, :email, :name, :phone, :lines, :password, :password_confirmation, :current_password)
  end
  
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    
  def home
  end
  
  def biz
  end
  
  def bizpricing
  end
  
  def perpricing
  end
  
  def about
  end
  
  def features
  end

  
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
    before_filter :authenticate_user!
    
    def new
        if current_user.whichmodel == "Business"
            if current_user.lines < 11
                planes = 101
            else
                planes = 102
            end
        else
            planes = 103
        end
    end
    
    def create
        if current_user.whichmodel == "Business"
            if current_user.lines < 11
                planes = 101
            else
                planes = 102
            end
        else
            planes = 103
        end
        
        @code = params[:couponCode]
        
        #gets the credit card details submitted in the form
        token = params[:stripeToken]
        
        if params[:couponCode] == ""
            customer = Stripe::Customer.create(
              card: token,
              quantity: current_user.lines,
              plan: planes,
              email: current_user.email
            )
        else
            #create a customer
            customer = Stripe::Customer.create(
              card: token,
              quantity: current_user.lines,
              plan: planes,
              coupon: @code,
              email: current_user.email
            )
        end
        
        current_user.subscribed = true
        current_user.stripeid = customer.id
        current_user.save
    
    
        redirect_to user_path(current_user.id), notice: "Your subscription was set up successfully!"
        
    end
    
    
    def index
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<header class="business-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h1 class="tagline">Get In Touch</h1>
            </div>
        </div>
    </div>
</header>

<section id="contact" class="bg-light section-p-lg">
    <div class="container wrapper-h-xs-lg reveal-bottom-opacity">
      <div class="row">

        <!-- Headline & Description -->
        <div class="col-md-8 col-md-offset-2 wrapper-v-lg text-center">

          <p>We will get back to you in 24 business hours.</p><br>
        </div>
        <div class="col-md-8 col-md-offset-2 wrapper-v-lg text-center">
            <div class="row">
                <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
              <div class="col-sm-6">
                 <div class="form-group" id="name-field">
                  <label for="form-name" class="sr-only">Name</label>
                  <%= f.input :name, :required => true, :class=> "form-control form-control-silver" %>
                </div>
                <!-- /End Input Name -->
              </div>
              
              <div class="col-sm-6">

                <!-- Input Email -->
                <div class="form-group" id="email-field">
                  <label for="form-email" class="sr-only">Email</label>
                  <%= f.input :email, :required => true, :class=> "form-control form-control-silver" %>
                </div>
                <!-- /End Input Email -->
              </div>
              
              <div class="col-sm-12">

                <!-- Input Message -->
                <div class="form-group" id="message-field">
                  <label for="form-message" class="sr-only">Message</label>
                  <%= f.input :message, :as => :text, :required => true, 
                  :class=>"form-control form-control-silver", :input_html => {:style=> 'width: 100%;', :rows => 10} %>
                </div>
                <!-- /End Input Message -->

                <!-- Message -->
                <div class="form-group">
                  <div id="message-contact" class="message text-center">
                    <span class="message-icon"><i class="fa fa-info"></i></span>
                    <span class="message-text"></span>
                  </div>
                </div>
                <!-- /End Message -->
                <div class= "hidden">
                      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
                </div>

                <!-- Submit Button -->
                <div class="form-group">
                  <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
                </div>
                <% end %>
                <!-- /End Submit Button -->

            </div>
          </div>
        </div>
      </div>
    </div>
</section>

app/views/layouts/_footer.html.erb
<footer id="footer" class="bg-dark section-p-sm text-white">
    <div class="container">
      <div class="row">

        <!-- Company Details -->
        <div class="col-md-6 wrapper-v-sm text-center-md">
          <p class="text-light">
            <a class="link-white" href="#">Terms</a>
            <span class="separator">|</span>
            <a class="link-white" href="#">Imprint</a>
            <span class="separator">|</span>
            <a class="link-white" href="#">Privacy
              Policy</a><br>
            © 2016 <%= image_tag("logo-white.png", :alt => "", :class => "logo-wrapper", :height => "18") %>.
            All Rights Reserved. Sources: <a class="link-white"
                                             href="" target="_blank"
                                             data-placement="top"
                                             data-toggle="tooltip" title="&copy; name1
  &copy; name2
  &copy; name3
  &copy; name4">dailholic</a>
          </p>
        </div>
        <!-- /End Company Details -->

        <!-- Buttons Social -->
        <div class="col-md-6 wrapper-v-sm text-right text-center-md">
            <p class="text-light">Tel.<a class="link-white" href="tel:018328292659">
               +1 832-829-2659</a></p>
        </div>
        
        <!-- /End Buttons Social -->

      </div>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<!-- Preloader -->


<!-- Main -->
<div id="page" class="light-version">


  <!-- ============================
       Navigation Header
  ================================= -->

  <header id="nav" class="light-nav">

    <!-- Sticky Navigation -->
    <!-- for static Navbar: remove navbar-fixed-top; add navbar-static-top and navbar-light-->
    <nav class="navbar navbar-static-top">
      <div class="container">
        <div class="navbar-header">

          <!-- Menu Button for Mobile Devices -->
          <button type="button" class="collapse navbar-toggle navbar-icon" data-toggle="collapse"
                  data-target="#navbar-collapse">
            <span></span>
            <span></span>
            <span></span>
          </button>

          <!-- Logo -->
          <a href="/" class="navbar-brand logo-color smooth-scroll"><span></span></a>

        </div>
        <!-- /End Navbar hero -->

        <div class="collapse navbar-collapse-md" id="navbar-collapse">

          <!-- Navigation Links -->
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Home", root_path %></li>
            <li><a href="#function" class="smooth-scroll">Function</a></li>
            <li><a href="#pricing" class="smooth-scroll">Pricing</a></li>
            <% if params[:action] == 'biz' %>
              <li><a href="/static/home" class="smooth-scroll">Residential</a></li>
            <% else params[:action] == 'home' %>
              <li><a href="/static/biz" class="smooth-scroll">Business</a></li>
            <% end %>
          </ul>

          <!-- Social Links -->
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_registration_path %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", new_user_session_path %></li>
            <% end %>
          </ul>
          <!-- /End Navigation Links -->

        </div>
        <!-- /End Navbar Collapse -->

      </div>
    </nav>
    <!-- /END Sticky Navigation -->

  </header>
</div>

app/views/layouts/_header1.html.erb
<!-- Preloader -->


<!-- Main -->
<div id="page" class="light-version">


  <!-- ============================
       Navigation Header
  ================================= -->

  <header id="nav" class="light-nav">

    <!-- Sticky Navigation -->
    <!-- for static Navbar: remove navbar-fixed-top; add navbar-static-top and navbar-light-->
    <nav class="navbar navbar-static-top navbar-light">
      <div class="container">
        <div class="navbar-header">

          <!-- Menu Button for Mobile Devices -->
          <button type="button" class="collapse navbar-toggle navbar-icon" data-toggle="collapse"
                  data-target="#navbar-collapse">
            <span></span>
            <span></span>
            <span></span>
          </button>

          <!-- Logo -->
          <a href="/home" class="navbar-brand logo-color smooth-scroll"><span></span></a>

        </div>
        <!-- /End Navbar hero -->

        <div class="collapse navbar-collapse-md" id="navbar-collapse">

          <!-- Navigation Links -->
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Home", root_path %></li>
            <li><a href="/features" class="smooth-scroll">Features</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Solution <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="/business" class="smooth-scroll">Business</a></li>
                  <li><a href="/residential" class="smooth-scroll">Residential</a></li>
                </ul>
              </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Pricing <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="/business_pricing" class="smooth-scroll">Business</a></li>
                  <li><a href="/residential_pricing" class="smooth-scroll">Residential</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Extra <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="/about" class="smooth-scroll">Why DH</a></li>
                  <li><a href="/contacts" class="smooth-scroll">Contact Us</a></li>
                </ul>
              </li>
          </ul>

          <!-- Social Links -->
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_registration_path %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", new_user_session_path %></li>
            <% end %>
          </ul>
          <!-- /End Navigation Links -->

        </div>
        <!-- /End Navbar Collapse -->

      </div>
    </nav>
    <!-- /END Sticky Navigation -->

  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Voip – Future of Communication</title>
    <meta name="description"
          content="Best phone service provider"/>
    <meta name="keywords"
          content="Voip, Phone, Phone Provider, Cheap Phone, Cloud Phone, UC"/>
    <meta name="author" content="Egotype">
    <%= stylesheet_link_tag    'application',"//fonts.googleapis.com/css?family=Lato:300,400,700,900,300italic,400italic,700italic,900italic",
              media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
<body>
  <% if content_for?(:navbar) %>
      <%= yield(:navbar) %>
    <% else %>
      <%= render 'layouts/header1' %>
    <% end %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>
    
    <%= render 'layouts/footer' %>

</body>
</html>

app/views/subscribers/_form.html.erb
<%= form_tag subscribers_path do %>

  <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
  <% end %>
  <p>
    <label class="amount">
      <p>Number of Users: <%= current_user.lines %></p>
      <% if current_user.whichmodel == "Business" %>
            <% if current_user.lines < 11 %>
                <p>Plan: Starter</p>
                <p>Period: 14 days free trial</p><br><br>
            <% else %>
                <p>Plan: High Volume</p>
                <p>Period: 14 days free trial</p><br><br>
            <% end %>
        <% else %>
            <p>Plan: Starter</p>
            <p>Period: 14 days free trial</p><br><br>
        <% end %>
      <%=link_to "Change Setting", edit_user_registration_path %>
    </label>
  </p>
  <p>
    <%= label_tag(:couponCode, 'Coupon:') %>
    <%= text_field_tag(:couponCode) %>
  </p>
  
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.application.secrets.stripe_publishable_key %>"
          data-description="A month's subscription"
          data-amount=""></script>
<% end %>

app/views/subscribers/index.html.erb
<h2>Thanks, you paid <strong>$29.00</strong>!</h2>

app/views/subscribers/new.html.erb
<div class="body-login-v2">
  <div class="login">
  		<div class="login-screen">
  		    <div class="app-title">
                <h1>Final Step</h1><br>
            </div>
                <h5>You are one step away from 14 days free trial</h5>  
                <%= render 'form' %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<header class="business-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h1 class="tagline"><%= @user.name %></h1>
            </div>
        </div>
    </div>
</header><br>


<div class="container">
  <div class="row">
    <div class="login">
        <h4>Email: <%= @user.email %></h4>
        <h4>Number of line: <%= @user.lines %></h4>
        <h4>Subscribtion Plan: <%= @user.whichmodel %></h4>
        <h4>Subscribtion Status: <%= @user.subscribed %></h4><br>
        <%=link_to "Edit Your Profile", edit_user_registration_path %>
    </div>
  </div>
</div>

app/views/users/show2.html.erb
<div class="body-login-v2">
  <div class="login">
  		<div class="login-screen">
  		    <div class="app-title">
                <h2><%= @user.name %></h2><br>
            </div>
            <h4>Email: <%= @user.email %></h4>
            <h4>Number of line: <%= @user.lines %></h4>
            <h4>Subscribtion Plan: <%= @user.whichmodel %></h4>
            <h4>Subscribtion Status: <%= @user.subscribed %></h4><br>
            <%=link_to "Edit Your Profile", edit_user_registration_path %>
        </div>
    </div>
</div>